/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

import com.sun.jdi.connect.spi.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.Locale;
import model.Ticket;

/**
 *
 * @author Amine
 */
public class Voyageurs extends javax.swing.JFrame {

    /**
     * Creates new form Voyageurs
     */
    public Voyageurs() {
        initComponents();
    }

    Ticket ticket = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gareDepart = new javax.swing.JComboBox<>();
        gareArrivee = new javax.swing.JComboBox<>();
        dateDepart = new com.toedter.calendar.JDateChooser();
        heureDepart = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        confort = new javax.swing.JComboBox<>();
        btnRechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GtTrajetTable = new javax.swing.JTable();
        btnAcheter = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trajets Valables SKAN ONCF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        gareDepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kenitra", "Rabat", "Fes", "Casa", "Marrakesh", "Tanger" }));

        gareArrivee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kenitra", "Rabat", "Fes", "Casa", "Marrakesh", "Tanger" }));

        dateDepart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateDepartPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Gare de Depart");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Gare D'Arrivée");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Date de Départ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Heure de  Départ");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Confort");

        confort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ère Classe", "2ème Classe" }));

        btnRechercher.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnRechercher.setText("Rechercher");
        btnRechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRechercherMouseClicked(evt);
            }
        });
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });

        GtTrajetTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GtTrajetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Gare de Départ", "Gare d'Arrivée", "Date de Départ", "Heure de Départ", "Confort"
            }
        ));
        GtTrajetTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GtTrajetTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GtTrajetTable);

        btnAcheter.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAcheter.setText("Acheter");
        btnAcheter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcheterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel2)
                .addGap(153, 153, 153)
                .addComponent(jLabel3)
                .addGap(174, 174, 174)
                .addComponent(jLabel4)
                .addGap(174, 174, 174)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(gareDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(gareArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(dateDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRechercher)
                        .addGap(94, 94, 94)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(heureDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(confort, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnAcheter, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gareDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gareArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dateDepart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heureDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confort, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcheter, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    java.sql.Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1 = null;
    Statement St = null, St1 = null;
    String date = "";

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        // TODO add your handling code here:
        /* SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(dateDepart.getDate());
        String heure = heureDepart.getValue().toString();
        String gareDep = gareDepart.getSelectedItem().toString();
        String gareArr = gareArrivee.getSelectedItem().toString();
        String conf = confort.getSelectedItem().toString();

        rechercherTrajets(gareDep, gareArr, date, heure, conf);*/
        AfficherTrajet();
    }//GEN-LAST:event_btnRechercherActionPerformed
    private void rechercherTrajets(String gareDep, String gareArr, String date, String heure, String confort) {
        /*try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trajets", "root", "");
            String query = "SELECT * FROM trajetstable WHERE gareDepart = ? AND gareArrivee = ? AND dateDepart = ? AND heureDepart = ? AND confort = ?";
            PreparedStatement pst = Con.prepareStatement(query);
            pst.setString(1, gareDep);
            pst.setString(2, gareArr);
            pst.setString(3, date);
            pst.setString(4, heure);
            pst.setString(5, confort);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) GtTrajetTable.getModel();
            model.setRowCount(0); // Pour vider la table avant d'ajouter de nouvelles lignes

            while (rs.next()) {
                // Assurez-vous que les indices des colonnes correspondent à votre structure de table
                Object[] row = new Object[]{rs.getString("gareDepart"), rs.getString("gareArrivee"), rs.getDate("dateDepart"), rs.getString("heureDepart"), rs.getString("confort")};
                model.addRow(row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erreur lors de la récupération des trajets");
        }*/
    }

    private void AfficherTrajet() {
        try {
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/trajets?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Africa/Casablanca", "root", "");
            Statement St = connection.createStatement();
            String sql = "select gareDepart, gareArrivee, dateDepart,heureDepart, confort from trajetstable where gareDepart = ? and gareArrivee = ? and dateDepart >=  ? and nbrPlaces >0 and confort = ?  ";
            PreparedStatement prest = connection.prepareStatement(sql);
            prest.setString(1, gareDepart.getSelectedItem().toString());
            prest.setString(2, gareArrivee.getSelectedItem().toString());
            prest.setInt(4, confort.getSelectedIndex());
            prest.setString(3, date);

            ResultSet result = prest.executeQuery();
            DefaultTableModel model = (DefaultTableModel) GtTrajetTable.getModel();
            model.setRowCount(0); // Clear existing data

            ResultSetMetaData rsmd = result.getMetaData();
            int columnCount = rsmd.getColumnCount();

            // Ensure model has the correct columns, only if it's empty
            if (model.getColumnCount() == 0) {
                for (int i = 1; i <= columnCount; i++) {
                    model.addColumn(rsmd.getColumnName(i));
                }
            }

            // Add data rows to the model
            while (result.next()) {
                Object[] row = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    row[i - 1] = result.getObject(i);
                }
                model.addRow(row);
            }
            result.close();
            prest.close();
            connection.close();
        } catch (Exception e) {
            System.out.println(" exception" + e.toString());
            e.printStackTrace();
        }

    }
    private void btnRechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRechercherMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_btnRechercherMouseClicked

    private void GtTrajetTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GtTrajetTableMouseClicked
        // TODO add your handling code here:
        int row = GtTrajetTable.getSelectedRow();
        String gareDepart = GtTrajetTable.getModel().getValueAt(row, 0).toString();
        String gareArrivee = GtTrajetTable.getModel().getValueAt(row, 1).toString();
        String dateDepart = GtTrajetTable.getModel().getValueAt(row, 2).toString();
        String heureDepart = GtTrajetTable.getModel().getValueAt(row, 3).toString();
        String confort = GtTrajetTable.getModel().getValueAt(row, 4).toString();
        if (confort.equals("1")) {
            confort = "2éme classe";
        } else {
            confort = "1er classe";
        }

        ticket = new Ticket(gareDepart, gareArrivee, dateDepart, heureDepart, confort);
    }//GEN-LAST:event_GtTrajetTableMouseClicked

    private void dateDepartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateDepartPropertyChange

        if ("date".equals(evt.getPropertyName())) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            date = sdf.format(dateDepart.getDate());
            System.out.println("date:" + date);
        } else {
            System.out.println("null");
        }
    }//GEN-LAST:event_dateDepartPropertyChange

    private void btnAcheterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcheterMouseClicked
        // TODO add your handling code here:
        new TicketView(ticket).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAcheterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voyageurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voyageurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voyageurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voyageurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voyageurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GtTrajetTable;
    private javax.swing.JButton btnAcheter;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JComboBox<String> confort;
    private com.toedter.calendar.JDateChooser dateDepart;
    private javax.swing.JComboBox<String> gareArrivee;
    private javax.swing.JComboBox<String> gareDepart;
    private javax.swing.JSpinner heureDepart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
